[www]
clear_env = no
env[TMPDIR] = /var/www/html/storage/framework/cache
php_admin_value[sys_temp_dir] = /var/www/html/storage/framework/cache
php_admin_value[upload_max_filesize] = 16M
php_admin_value[post_max_size] = 128M
php_admin_value[max_file_uploads] = 40
php_admin_value[memory_limit] = 256M
php_admin_value[max_execution_time] = 180
php_admin_value[max_input_time] = 180
php_admin_value[max_input_vars] = 5000
