[PHP]
sys_temp_dir = /var/www/html/storage/framework/cache
error_reporting = 6143

; Mejora notable en Docker + bind mount (Windows/Mac).
opcache.enable = 1
opcache.enable_cli = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
opcache.max_accelerated_files = 20000
opcache.memory_consumption = 128
